include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [example/explorer/**, tool/winmd/**]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
    
linter:
  rules:
    # Some additional lints we want to enforce
    omit_local_variable_types: true
    prefer_expression_function_bodies: true
    prefer_interpolation_to_compose_strings: true
    prefer_relative_imports: true
    unnecessary_lambdas: true